### ISSUE TITLE
Mod crashes with Forge >36.1.36 and 36.2

### ISSUE THREAD

**Issue by Sushant-Padha** [jediminer543/JMT-MCMT#77] opened 2021-07-23 03:18 UTC
When using MCMT mod version [1.16.5-0.21.80](https://www.curseforge.com/minecraft/mc-mods/mcmt-multithreading/files/3355677), the mod crashes with Forge version higher than 36.1.36 and lower than 36.2

Edit: Now it also crashes with Forge 36.2

_(Is this really a problem though? Because one can just switch to Forge 36.1.36)_

Here is the [crash report](https://gist.github.com/Sushant-Padha/9c362a64d70a70bcaba06cb42c6b8320).

**Comment by EimisM** [comment] 2021-07-27 09:50
Same here, just installed the mod and it crashes on the startup

**Comment by zoyer2** [comment] 2021-07-30 03:15
yep same here

**Comment by jediminer543** [comment] 2021-08-07 12:24
This issue was caused by forge deciding to change the damn local variables

This has now been fixed in the main repo

**Comment by TheSnowyChickens** [comment] 2021-08-16 21:16
Hello :)
could you maybe upload the updated version to curse ? :(

**Comment by NXTler** [comment] 2021-08-17 05:50
@TheSnowyChickens , you can download the last dev version from actions in GitHub, or from our discord server.

**Comment by jediminer543** [comment] 2021-09-05 17:46
Fix will be pushed to curseforge after current release has finished testing so am closing now

**Closed by jediminer543** 2021-09-05 17:46 UTC
