### ISSUE TITLE
Mod not working in lastest forge

### ISSUE THREAD

**Issue by rjulib00** [jediminer543/JMT-MCMT#84] opened 2021-09-08 18:18 UTC
Mod doesnt work.

jmt_mcmt-1.16.5-0.21.80
forge 36.2.4

as soons as i try to enter a singleplayer world, or create a new one, game crashes

**Comment by KubiRemPL** [comment] 2021-09-08 18:19
Can you please share us more details like latest.log file?

**Comment by JT122406** [comment] 2021-09-09 00:19
[latest.log](https://github.com/jediminer543/JMT-MCMT/files/7132441/latest.log)
[crash-2021-09-08_20.16.50-server.txt](https://github.com/jediminer543/JMT-MCMT/files/7132444/crash-2021-09-08_20.16.50-server.txt)

**Comment by JT122406** [comment] 2021-09-09 00:20
Here are my logs on the latest version of Forge for 1.16.5 there is nothing else on this server besides MCMT

**Comment by meta1203** [comment] 2021-09-09 01:11
This is caused by an issue fixed in the latest dev version. Either compile it yourself, or visit the Discord server to grab the very latest version from the dev-artifacts channel.

**Comment by JT122406** [comment] 2021-09-09 03:20
So im trying the latest dev version rn and it's pinning all my cores at 100% with no one on the server

**Comment by JT122406** [comment] 2021-09-09 04:41
now my issue is it's impossible to join the server since now its lagging due to the 100% pin

**Comment by jediminer543** [comment] 2021-09-09 16:24
Very odd; please provide additional details if possible

I also suggest toggling the settings: enableblankreturn=true, enablechunktimeout=true

**Comment by JT122406** [comment] 2021-09-09 18:20
Changing those 2 settings got it to work but it still seems to be lagging luckly its not pinning all my corese like it was before here is log:
[latest.log](https://github.com/jediminer543/JMT-MCMT/files/7138885/latest.log)
it crashed at the end also fyi performant is installed however I changed the entity multithreading which i heard makes it compatible with this but I can remove it and try again.

**Comment by RHSD** [comment] 2021-09-14 09:25
[latest.log](https://github.com/jediminer543/JMT-MCMT/files/7160560/latest.log)
I used a kill command you can search for "kill" and find where it took place.
I experienced the same bee spamming bug with Performant and MCMT installed alongside tons of other mods.
On performant multiEntities = false
On MCMT disableWorld = true, disableWorldPostTick = true, enableChunkTimeout = true, enableBlankReturn = true

**Comment by jediminer543** [comment] 2021-09-14 09:30
Performant is considered incompatible; I suggest removing it and trying again

Also this issue is distinct from the original issue which was a bytecode level issue with new forge so please create a new issue

Sorry for the inconvenience and if it still happens without performant please send me more details as I have heard of a similar issue caused by a different set of mods

**Closed by jediminer543** 2021-09-14 09:30 UTC
