### ISSUE TITLE
minecraft crashes on world creation

### ISSUE THREAD

**Issue by benjiyk** [jediminer543/JMT-MCMT#76] opened 2021-07-22 17:49 UTC
Minecraft version- 1.16.5

mods installed- just this one

java version 1.8.0_301

**Comment by NXTler** [comment] 2021-07-22 19:03
Can we get the Crashlog?

**Comment by benjiyk** [comment] 2021-07-22 19:06
It doesn’t hand one

**Comment by benjiyk** [comment] 2021-07-22 20:01
[crash-2021-07-22_13.42.01-server.txt](https://github.com/jediminer543/JMT-MCMT/files/6864930/crash-2021-07-22_13.42.01-server.txt)

**Comment by benjiyk** [comment] 2021-07-22 20:02
that is the crash file above

**Comment by Sushant-Padha** [comment] 2021-08-01 12:35
I have highlighted this problem in issue #77 

Basically, this crashes because MCMT does not even work with a Forge version higher than 36.1.36

**Comment by jediminer543** [comment] 2021-09-05 17:47
Duplicate of #77 as said; closing

**Closed by jediminer543** 2021-09-05 17:47 UTC
