### ISSUE TITLE
Sudden server crash 

### ISSUE THREAD

**Issue by smonnnn** [jediminer543/JMT-MCMT#5] opened 2020-08-22 21:42 UTC
Log: https://paste.ee/p/fZK2g

This happened after teleporting to a village. I don't have much else really.

**Comment by jediminer543** [comment] 2020-08-25 07:20
Sorry for the delay in the repsonse;

The issue is caused by `LevelBasedGraph.processUpdates(I)I` because LevelBasedGraph uses FastUtil and FastUtil is bad.

I've been looking into replacing the fast util components in it anyway, so I'll hopefully have that done soon and then it should work again

**Comment by jediminer543** [comment] 2020-08-31 18:13
This should be fixed by bd79cf4b08cc89de2da7803db6e3857c32c3e5bc as that targets the dodgy collection causing the crash

**Closed by jediminer543** 2020-08-31 18:13 UTC
Labels: bug, fast util
